### ISSUE TITLE
Overflow issue in result  details page

### ISSUE THREAD

**Issue by sakibovi123** [sakibovi123/wrestling_news_app#7]
====================================================================================================
Reloaded 1 of 1375 libraries in 949ms (compile: 31 ms, reload: 297 ms, reassemble: 570 ms).

**Comment by FaizAhamed2o1** [comment]
Expanded(
              child: ListView.builder(
                physics: const ClampingScrollPhysics(),
                shrinkWrap: true,
                itemCount: 8,
                itemBuilder: (context, index) {
                  return Container(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Html(data: resultDescription),
                        // Text(
                        //   resultDescription,
                        //   style: const TextStyle(
                        //     fontSize: 16,
                        //     fontWeight: FontWeight.w600,
                        //   ),
                        // ),
                        const SizedBox(
                          height: 10,
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),

**Comment by sakibovi123** [comment]
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:wrestling_news_app/Controller/NewsController.dart';
import 'package:wrestling_news_app/Controller/ResultController.dart';

import '../Pages/Export.dart';

class ResultDetails extends StatefulWidget {
  static const routeName = "/result-details";
  const ResultDetails({
    Key? key,
  }) : super(key: key);

  @override
  State<ResultDetails> createState() => _ResultDetailsState();
}

class _ResultDetailsState extends State<ResultDetails> {
  int _initialPage = 0;
  @override
  Widget build(BuildContext context) {
    PageController pageController = PageController(
        initialPage: _initialPage, keepPage: true, viewportFraction: 1.0);
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;
    final id = ModalRoute.of(context)?.settings.arguments;
    final resultDetails =
      Provider.of<ResultsController>(context).getResultDetails(id as int);
    return Scaffold(
      body: Stack(
        children: [
          SingleChildScrollView(
            physics: ClampingScrollPhysics(),
            scrollDirection: Axis.vertical,
            child: ShowResultCard(
              width: width,
              height: height,
              resultTitle: resultDetails.title!.rendered!,
              resultDescription: resultDetails.content!.rendered!,
            ),
          ),
          CustomAppbar(),
        ],
      ),
    );
  }
}

**Comment by sakibovi123** [comment]
Widget build(BuildContext context) {
    return UnconstrainedBox(
      child: Container(
        margin: const EdgeInsets.only(top: 30),
        width: width,
        height: height * 0.95,
        padding: const EdgeInsets.symmetric(horizontal: 10.0),
        child: Column(
          children: [
            Container(
              margin: const EdgeInsets.only(top: 30),
              padding: const EdgeInsets.only(
                bottom: 0, // Space between underline and text
              ),
              decoration: const BoxDecoration(
                border: Border(
                  bottom: BorderSide(
                    color: Colors.grey,
                    width: 2.0, // Underline thickness
                  ),
                ),
              ),
              child: Text(
                resultTitle,
                style: const TextStyle(
                  color: Colors.black,
                  fontSize: 26,
                  fontWeight: FontWeight.w900,
                ),
              ),
            ),
            const SizedBox(
              height: 10,
            ),
            Container(
              margin: const EdgeInsets.symmetric(
                horizontal: 10,
              ),
              child: ListView.builder(
                scrollDirection: Axis.vertical,
                physics: const ClampingScrollPhysics(),
                shrinkWrap: true,
                itemCount: 8,
                itemBuilder: (context, index) {
                  return Container(
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Html(data: resultDescription),
                        // Text(
                        //   resultDescription,
                        //   style: const TextStyle(
                        //     fontSize: 16,
                        //     fontWeight: FontWeight.w600,
                        //   ),
                        // ),
                        const SizedBox(
                          height: 10,
                        ),
                      ],
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }

**Comment by FaizAhamed2o1** [comment]
import 'package:flutter/material.dart';

class ChampionsCard extends StatelessWidget {
  final double width;
  final double height;
  final String titleName;
  final String currentChampion;
  final String since;
  final String? titleImage;
  final String? championImage;

  const ChampionsCard(
      {Key? key,
      required this.width,
      required this.height,
      required this.titleName,
      required this.currentChampion,
      required this.since,
      this.titleImage,
      this.championImage})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return UnconstrainedBox(
      child: Container(
        margin: EdgeInsets.only(bottom: 10, top: 10),
        width: width * 0.95,
        height: height * 0.30,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(5),
          boxShadow: const [
            BoxShadow(
              offset: Offset(0, 8),
              spreadRadius: -12,
              blurRadius: 26,
              color: Color.fromRGBO(149, 143, 143, 1),
            ),
          ],
        ),
        child: Container(
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Container(
                margin: EdgeInsets.only(top: 5),
                width: width * 0.20,
                height: height * 0.20,
                child: titleImage != null
                    ? Image.network(
                        'https://wrestlingdb.pythonanywhere.com/$titleImage',
                        fit: BoxFit.contain,
                      )
                    : Image.network(
                        "https://wallpapercave.com/wp/wp2092436.jpg"),
              ),
              Container(
                height: height * .28,
                child: Column(
                  children: [
                    const SizedBox(
                      height: 30,
                    ),
                    Container(
                      color: const Color(0xFFce061e),
                      child: Padding(
                        padding: const EdgeInsets.symmetric(
                            vertical: 5, horizontal: 10),
                        child: Text(
                          titleName,
                          style: const TextStyle(
                            color: Color(0xFFfffffff),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 20,
                    ),
                    Container(
                      width: width * 0.5,
                      child: Column(
                        children: [
                          Text(
                            'CUREENT CHAMPION: $currentChampion',
                            textAlign: TextAlign.center,
                          ),
                          Text('SINCE: $since'),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                margin: EdgeInsets.only(top: 5),
                width: width * 0.20,
                height: height * 0.20,
                child: championImage != null
                    ? Image.network(
                        'https://wrestlingdb.pythonanywhere.com/$championImage',
                        fit: BoxFit.contain,
                      )
                    : Image.network(
                        "https://t4.ftcdn.net/jpg/02/51/95/53/360_F_251955356_FAQH0U1y1TZw3ZcdPGybwUkH90a3VAhb.jpg"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

**Comment by sakibovi123** [comment]
import 'package:flutter/material.dart';
import 'package:wrestling_news_app/Controller/ChampionController.dart';

import '../Pages/Export.dart';

class Champions extends StatefulWidget {
  const Champions({
    Key? key,
  }) : super(key: key);

  static const routeName = '/Champions';
  @override
  State<Champions> createState() => _ChampionsState();
}

ChampionController championController = ChampionController();

class _ChampionsState extends State<Champions> {
  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
      ),
      body: FutureBuilder(
        future: championController.getChampions(),
        builder: (context, snapshot) {
          if( snapshot.hasData ){
            return ListView.builder(
              itemCount: 10,
              scrollDirection: Axis.vertical,
              physics: ClampingScrollPhysics(),
              itemBuilder: (context, index) {
                return ChampionsCard(
                  width: width,
                  height: height,
                  titleName: snapshot.data[index]["title"],
                  currentChampion: snapshot.data[index]["current_champion"],
                  since: snapshot.data[index]["since"],
                  titleImage: snapshot.data[index]["title_image"],
                  championImage: snapshot.data[index]["champion_image"],
                );
              },
            );
          }
          else{
            return const Center(
              child: CircularProgressIndicator(),
            );
          }


        }
      ),
    );
  }
}

**Comment by sakibovi123** [comment]
import 'package:flutter/material.dart';

class ChampionsCard extends StatelessWidget {
  final double width;
  final double height;
  final String titleName;
  final String currentChampion;
  final String since;
  final String? titleImage;
  final String? championImage;

  const ChampionsCard(
      {Key? key,
        required this.width,
        required this.height,
        required this.titleName,
        required this.currentChampion,
        required this.since,
        this.titleImage,
        this.championImage})
      : super(key: key);

  @override
  Widget build(BuildContext context) {
    return UnconstrainedBox(
      child: Container(
        margin: EdgeInsets.only(bottom: 10, top: 10),
        width: width * 0.95,
        height: height * 0.30,
        decoration: BoxDecoration(
          color: Colors.white,
          borderRadius: BorderRadius.circular(5),
          boxShadow: const [
            BoxShadow(
              offset: Offset(0, 8),
              spreadRadius: -12,
              blurRadius: 26,
              color: Color.fromRGBO(149, 143, 143, 1),
            ),
          ],
        ),
        child: Container(
          child: Row(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Container(
                margin: EdgeInsets.only(top: 5),
                width: width * 0.20,
                height: height * 0.20,
                child: titleImage != null
                    ? Image.network(
                  'https://wrestlingdb.pythonanywhere.com/$titleImage',
                  fit: BoxFit.contain,
                )
                    : Image.network(
                    "https://wallpapercave.com/wp/wp2092436.jpg"),
              ),
              Container(
                height: height * .28,
                child: Column(
                  children: [
                    const SizedBox(
                      height: 30,
                    ),
                    Container(
                      color: const Color(0xFFce061e),
                      child: Padding(
                        padding: const EdgeInsets.symmetric(
                            vertical: 5, horizontal: 10),
                        child: Text(
                          titleName,
                          style: const TextStyle(
                            color: Color(0xFFfffffff),
                          ),
                        ),
                      ),
                    ),
                    const SizedBox(
                      height: 20,
                    ),
                    Container(
                      width: width * 0.5,
                      child: Column(
                        children: [
                          Text(
                            'CUREENT CHAMPION: $currentChampion',
                            textAlign: TextAlign.center,
                          ),
                          Text('SINCE: $since'),
                        ],
                      ),
                    ),
                  ],
                ),
              ),
              Container(
                margin: EdgeInsets.only(top: 5),
                width: width * 0.20,
                height: height * 0.20,
                child: championImage != null
                    ? Image.network(
                  'https://wrestlingdb.pythonanywhere.com/$championImage',
                  fit: BoxFit.contain,
                )
                    : Image.network(
                    "https://t4.ftcdn.net/jpg/02/51/95/53/360_F_251955356_FAQH0U1y1TZw3ZcdPGybwUkH90a3VAhb.jpg"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
